<?php

namespace AppBundle\Repository;

/**
 * AdherantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdherentRepository extends \Doctrine\ORM\EntityRepository
{
	public function findNotBenevole() {
		return $this->getEntityManager()
			->createQuery(
				'SELECT a FROM AppBundle:Adherent a WHERE a.id NOT IN(SELECT b.id FROM AppBundle:Benevole b)'
			)
			->getResult();
	}
}
