<?php

namespace AppBundle\Repository;

/**
 * AdherantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdherantRepository extends \Doctrine\ORM\EntityRepository
{
}
