<?php

namespace AppBundle\Repository;

/**
 * AmapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmapRepository extends \Doctrine\ORM\EntityRepository
{
}
