<?php

namespace AppBundle\Repository;

/**
 * Methode_ReglementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Methode_ReglementRepository extends \Doctrine\ORM\EntityRepository
{
}
