# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_db:
            entity:
                class: AppBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        gettoken:
            pattern:    ^/api/login
            stateless:  true
            gfreeau_get_jwt:
                username_parameter:         username
                password_parameter:         password
                post_only:                  true
                authentication_provider:    security.authentication.provider.dao
                user_checker:               security.user_checker 
                success_handler:            lexik_jwt_authentication.handler.authentication_success
                failure_handler:            lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            anonymous: ~
            lexik_jwt: ~

    access_control:
        - { path: ^/api/login,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/lost-pass,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,            roles: IS_AUTHENTICATED_FULLY }
