amap:
    type: rest
    resource: "@AppBundle/Controller/AmapsController.php"
    name_prefix:  api_
    options:
        expose: true

produit:
    type: rest
    resource: "@AppBundle/Controller/ProduitsController.php"
    name_prefix:  api_
    options:
        expose: true

login_check:
    path: /login_check