amap:
    type: rest
    resource: "@AppBundle/Controller/AmapsController.php"
    name_prefix:  api_
    options:
        expose: true

produit:
    type: rest
    resource: "@AppBundle/Controller/ProduitsController.php"
    name_prefix:  api_
    options:
        expose: true

producteur:
    type: rest
    resource: "@AppBundle/Controller/ProducteursController.php"
    name_prefix:  api_
    options:
        expose: true

adherent:
    type: rest
    resource: "@AppBundle/Controller/AdherentsController.php"
    name_prefix:  api_
    options:
        expose: true

contrat:
    type: rest
    resource: "@AppBundle/Controller/ContratsController.php"
    name_prefix:  api_
    options:
        expose: true

reglement:
    type: rest
    resource: "@AppBundle/Controller/ReglementsController.php"
    name_prefix:  api_
    options:
        expose: true

methodereglement:
    type: rest
    resource: "@AppBundle/Controller/MethodesReglementsController.php"
    name_prefix:  api_
    options:
        expose: true

benevole:
    type: rest
    resource: "@AppBundle/Controller/BenevolesController.php"
    name_prefix:  api_
    options:
        expose: true

stock:
    type: rest
    resource: "@AppBundle/Controller/StocksController.php"
    name_prefix:  api_
    options:
        expose: true

post:
    resource: "@AppBundle/Controller/AuthController.php"
    type:     annotation
