amap:
    type: rest
    resource: "@AppBundle/Controller/AmapsController.php"
    name_prefix:  api_
    options:
        expose: true

produit:
    type: rest
    resource: "@AppBundle/Controller/ProduitsController.php"
    name_prefix:  api_
    options:
        expose: true

producteur:
    type: rest
    resource: "@AppBundle/Controller/ProducteursController.php"
    name_prefix:  api_
    options:
        expose: true

adherent:
    type: rest
    resource: "@AppBundle/Controller/AdherentsController.php"
    name_prefix:  api_
    options:
        expose: true

contrat:
    type: rest
    resource: "@AppBundle/Controller/ContratsController.php"
    name_prefix:  api_
    options:
        expose: true

post:
    resource: "@AppBundle/Controller/AuthController.php"
    type:     annotation
